apiVersion: v1
kind: Service
metadata:
  name: ex-cluster
  labels:
    app: ex-cluster
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: ex-cluster
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ex-cluster
spec:
  selector:
    matchLabels:
      app: ex-cluster
  serviceName: "ex-cluster"
  replicas: 2
  template:
    metadata:
      labels:
        app: ex-cluster
    spec:
      containers:
        - name: ex-cluster
          # the same name and tag must be used when building the image
          image: ex_cluster:local
          # # use Never so the image is grabbed locally, for demo purposes
          imagePullPolicy: Never
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_COOKIE
              value: "cookie"